# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TwoCents' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Database', '~> 5.15.0'
  pod 'Firebase/Messaging', '~> 5.15.0'

  # Pods for TwoCents

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'TwoCentsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TwoCents-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TwoCents-tvOS

  target 'TwoCents-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
