export const SHOW_DIALOG = "SHOW_DIALOG";
export const HIDE_DIALOG = "HIDE_DIALOG";

export const LOG_OUT_FROM_APP = "LOG_OUT_FROM_APP";

//VerifyCOnstants

export const INITIAL_VERFICATION_STATE = "INITIAL_VERFICATION_STATE";
export const VERIFYING = "VERIFYING";
export const VERIFYING_SUCCESS = "VERIFYING_SUCCESS";
export const VERIFYING_FAILURE = "VERIFYING_FAILURE";


//LoginConstants
export const FETCHING_LOGIN = "FETCHING_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//HelpCenter Constants

export const FETCHING_HELP_CENTER = "FETCHING_HELP_CENTER";
export const HELP_CENTER_SUCCESS = "HELP_CENTER_SUCCESS";
export const HELP_CENTER_FAILURE = "HELP_CENTER_FAILURE";


//Messaging Constants
export const FETCHING_STOPPED_USERS_FOR_MESSAGE = "FETCHING_STOPPED_USERS_FOR_MESSAGE";
export const FETCHING_USERS_FOR_MESSAGE = "FETCHING_USERS_FOR_MESSAGE";
export const USER_FROM_FIREBASE = "USER_FROM_FIREBASE";


//FollowerFollowing
export const ACCEPT_REJECT_USER = "ACCEPT_REJECT_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const FOLLOW_UNFOLLOW_USERS = "FOLLOW_UNFOLLOW_USERS";
export const FETCHING_FOLLOWER = "FETCHING_FOLLOWER";
export const HIDE_FETCHING_FOLLOWER = "HIDE_FETCHING_FOLLOWER";
export const FETCH_FOLLOWER_SUCCESS = "FETCH_FOLLOWER_SUCCESS";
export const FETCH_FOLLOWER_FAILURE = "FETCH_FOLLOWER_FAILURE";

// HomeConstants
export const HIDE_DIALOGS_HOME = "HIDE_DIALOGS_HOME";
export const HIDE_FETCHING_HOME = "HIDE_FETCHING_HOME";
export const FETCHING_HOME = "FETCHING_HOME";
export const FETCH_HOME_SUCCESS = "FETCH_HOME_SUCCESS";
export const FETCH_HOME_FAILURE = "FETCH_HOME_FAILURE";
export const SHOW_HOME_SHARE_DIALOG = "SHOW_HOME_SHARE_DIALOG";
export const POST_DELETED_SUCCESSFULLY = "POST_DELETED_SUCCESSFULLY";
export const UPDATE_INDEX_IN_HOME = "UPDATE_INDEX_IN_HOME";
export const BLOCKED_USER_POST = "BLOCKED_USER_POST";

//SinglePost Constants
export const SINGLE_POST_INITIALIZE = "SINGLE_POST_INITIALIZE";
export const FETCHING_SINGLE_POST = "FETCHING_SINGLE_POST";
export const HIDE_FETCHING_SINGLE_POST = "HIDE_FETCHING_SINGLE_POST";
export const FETCH_SUCCESS_SINGLE_POST = "FETCH_SUCCESS_SINGLE_POST";
export const FETCH_FAILURE_SINGLE_POST = "FETCH_FAILURE_SINGLE_POST";
export const SHOW_SHARE_DIALOG_SINGLE_POST = "SHOW_SHARE_DIALOG_SINGLE_POST";
export const SINGLE_POST_DELETED_SUCCESSFULLY = "SINGLE_POST_DELETED_SUCCESSFULLY";
export const BLOCKED_USER_SINGLE_POST = "BLOCKED_USER_SINGLE_POST";
export const BLOCKED_USER_FROM_COMMENT_SINGLE_POST = "BLOCKED_USER_FROM_COMMENT_SINGLE_POST";
export const SINGLE_POST_DELETED_COMMENT = "SINGLE_POST_DELETED_COMMENT";

//UploadConstants
export const UPLOADING = "UPLOADING";
export const INITIAL_STATE = "INITIAL_STATE";
export const UPLOADING_SUCCESS = "UPLOADING_SUCCESS";
export const UPLOADING_FAILURE = "UPLOADING_FAILURE";

//User Credentials
export const FETCHING_STATUS = "FETCHING_STATUS";
export const FETCH_STATUS_SUCCESS = "FETCH_STATUS_SUCCESS";
export const FETCH_STATUS_FAILURE = "FETCH_STATUS_FAILURE";

//Search Screen Constants 
export const FETCHING_SEARCH = "FETCHING_SEARCH";
export const HIDE_FETCHING_SEARCH = "HIDE_FETCHING_SEARCH";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_FAILURE = "FETCH_SEARCH_FAILURE";
export const SHOW_SEARCH_SHARE_DIALOG = "SHOW_SEARCH_SHARE_DIALOG";
export const HIDE_SEARCH_SHARE_DIALOG = "HIDE_SEARCH_SHARE_DIALOG";
export const UPDATE_SEARCH_INDEX = "UPDATE_SEARCH_INDEX";
export const BLOCKED_USER_POST_SEARCH = "BLOCKED_USER_POST_SEARCH";
export const POST_DELETED_SUCCESSFULLY_SEARCH = "POST_DELETED_SUCCESSFULLY_SEARCH";
export const INITIAL_STATE_SEARCH_DETAIL = "INITIAL_STATE_SEARCH_DETAIL";

export const SEARCHED_KEY_SUCCESS = "SEARCHED_KEY_SUCCESS";
export const SEARCHED_KEY_FAILURE = "SEARCHED_KEY_FAILURE";


//SearchDetail Screen Constants
export const FETCHING_SEARCH_DETAIL = "FETCHING_SEARCH_DETAIL";
export const HIDE_FETCHING_SEARCH_DETAIL = "HIDE_FETCHING_SEARCH_DETAIL";
export const SEARCHED_RESULT_FOR_HASTAG_AND_STRINGS = "SEARCHED_RESULT_FOR_HASTAG_AND_STRINGS";
export const SEARCHED_RESULT_FOR_HASTAG_AND_STRINGS_ERROR = "SEARCHED_RESULT_FOR_HASTAG_AND_STRINGS_ERROR";
export const HIDE_SEARCH_DETAIL_SHARE_DIALOG = "HIDE_SEARCH_DETAIL_SHARE_DIALOG";
export const SHOW_SEARCH_DETAIL_SHARE_DIALOG = "SHOW_SEARCH_DETAIL_SHARE_DIALOG";
export const UPDATE_SEARCH_DETAIL_INDEX = "UPDATE_SEARCH_DETAIL_INDEX";
export const POST_DELETED_SUCCESSFULLY_SEARCH_DETAIL = "POST_DELETED_SUCCESSFULLY_SEARCH_DETAIL";
export const BLOCKED_USER_POST_SEARCH_DETAIL = "BLOCKED_USER_POST_SEARCH_DETAIL";
export const SEARCH_DETAIL_FOLLOW_UNFOLLOW = "SEARCH_DETAIL_FOLLOW_UNFOLLOW";


export const UPDATED_NOTIFICATION_SUCCESS = "UPDATED_NOTIFICATION_SUCCESS";
export const UPDATED_NOTIFICATION_FAILURE = "UPDATED_NOTIFICATION_FAILURE";

//Profile constants
export const PROFILE_FETCHING = "PROFILE_FETCHING";
export const PROFILE_FETCHING_DONE = "PROFILE_FETCHING_DONE";
export const PROFILE_DATA_SUCCESS = "PROFILE_DATA_SUCCESS";
export const PROFILE_DATA_FAILURE = "PROFILE_DATA_FAILURE";
export const SHOW_PROFILE_POST_DIALOG = "SHOW_PROFILE_POST_DIALOG";
export const UPDATE_INDEX_PROFILE = "UPDATE_INDEX_PROFILE";
export const UPDATE_ANOTHER_USER_PROFILE = "UPDATE_ANOTHER_USER_PROFILE";
export const POST_DELETED_SUCCESSFULLY_PROFILE = "POST_DELETED_SUCCESSFULLY_PROFILE";
export const BLOCKED_USER_POST_PROFILE = "BLOCKED_USER_POST_PROFILE";


//BookMarkConstants
export const FETCHING_BOOKMARK = "FETCHING_BOOKMARK";
export const HIDE_FETCHING_BOOKMARK = "HIDE_FETCHING_BOOKMARK";
export const FETCHED_BOOKMARK_SUCCESS = "FETCHED_BOOKMARK_SUCCESS";
export const FETCH_BOOKMARK_FAILURE = "FETCH_BOOKMARK_FAILURE";
export const SHOW_SHARE_DIALOG_BOOKMARK = "SHOW_SHARE_DIALOG_BOOKMARK";
export const UPDATE_INDEX_IN_BOOKMARK = "UPDATE_INDEX_IN_BOOKMARK";
export const BOOKMARK_DELETED_SUCCESSFULLY = "BOOKMARK_DELETED_SUCCESSFULLY";
export const BLOCKED_USER_BOOKMARK = "BLOCKED_USER_BOOKMARK";
export const REMOVE_BOOKMARK = "REMOVE_BOOKMARK";

//CreateListConstant
export const FETCHING_LIST = "FETCHING_LIST";
export const HIDE_DIALOG_FETCHING_LIST = "HIDE_DIALOG_FETCHING_LIST";
export const FETCH_SUCCESS_LIST = "FETCH_SUCCESS_LIST";
export const FETCH_FAILURE_LIST = "FETCH_FAILURE_LIST";
export const CREATE_LIST_SUCCESS = "CREATE_LIST_SUCCESS";
export const LIST_DETAIL_SUCCESS = "LIST_DETAIL_SUCCESS";
export const LIST_DETAIL_FAILURE = "LIST_DETAIL_FAILURE";
export const SEARCH_DETAIL_SUCCESS = "SEARCH_DETAIL_SUCCESS";
export const ADD_DELETE_SUCCESS = "ADD_DELETE_SUCCESS";
export const SET_CREATED_FALSE = "SET_CREATED_FALSE";
export const DELETE_LIST_SUCCESS = "DELETE_LIST_SUCCESS";
export const DELETE_LIST_FAILURE = "DELETE_LIST_FAILURE";
export const SUBSCRIBE_UNSUBSCRIBE_LIST = "SUBSCRIBE_UNSUBSCRIBE_LIST";
export const BLOCKED_USER_POST_LIST = "BLOCKED_USER_POST_LIST";
export const POST_DELETED_SUCCESSFULLY_LIST = "POST_DELETED_SUCCESSFULLY_LIST";
export const SHOW_LIST_SHARE_DIALOG = "SHOW_LIST_SHARE_DIALOG";
export const UPDATE_INDEX_IN_LIST = "UPDATE_INDEX_IN_LIST";
export const HIDE_DIALOGS_LIST = "HIDE_DIALOGS_LIST";



//Instant Constant
export const HIDE_LOADER_MOMENTS = "HIDE_LOADER_MOMENTS";
export const FETCHING_MOMENT = "FETCHING_MOMENT";
export const MOMENT_DATA_SUCCESS = "MOMENT_DATA_SUCCESS";
export const MOMENT_DATA_FAILURE = "MOMENT_DATA_FAILURE";
export const MOMENT_DETAIL_SUCCESS = "MOMENT_DETAIL_SUCCESS";
export const MOMENT_DETAIL_FAILURE = "MOMENT_DETAIL_FAILURE";
export const UPDATE_LIKE_STATUS = "UPDATE_LIKE_STATUS";
export const DELETE_MOMENT_SUCCESS = "DELETE_MOMENT_SUCCESS";
export const DELETE_ATTACHED_TWEET_MOMENT_SUCCESS = "DELETE_ATTACHED_TWEET_MOMENT_SUCCESS";
export const NO_MOMENT_AVAILABLE = "NO_MOMENT_AVAILABLE";


// Setting Constant
export const FETCHING_SETTNGS = "FETCHING_SETTNGS";
export const SUCCESS_SETTING_DATA = "SUCCESS_SETTING_DATA";
export const FAILURE_SETTING_DATA = "FAILURE_SETTING_DATA";
export const INITIALIZE_SETTING_REDUCER = "INITIALIZE_SETTING_REDUCER";


// AccountSetting Constants
export const UPDATING_PROFILE_DATA_SETTING = "UPDATING_PROFILE_DATA_SETTING";
export const CHANGES_USER_DATA_SUCCESS = "CHANGES_USER_DATA_SUCCESS";
export const CHANGES_USER_DATA_FAILURE = "CHANGES_USER_DATA_FAILURE";
export const SHOW_DIALOG_ACCOUNT = "SHOW_DIALOG_ACCOUNT";
export const GO_TO_LOGIN = "GO_TO_LOGIN";
export const HIDE_DIALOG_ACCOUNT = "HIDE_DIALOG_ACCOUNT";

// BlockList Constants
export const UPDATING_BLOCK_LIST = "UPDATING_BLOCK_LIST";
export const REMOVE_USER_FROM_BLOCKED_LIST = "REMOVE_USER_FROM_BLOCKED_LIST";
export const REMOVING_USER_FROM_BLOCKED_LIST_FAILURE = "REMOVING_USER_FROM_BLOCKED_LIST_FAILURE";
export const REMOVE_USER_FROM_MUTE_LIST = "REMOVE_USER_FROM_MUTE_LIST";
export const REMOVING_USER_FROM_MUTE_LIST_FAILURE = "REMOVING_USER_FROM_MUTE_LIST_FAILURE";

//Privacy Constants
export const UPDATING_USER_PRIVACY = "UPDATING_USER_PRIVACY";
export const UPDATING_PRIVACY_SUCCESS = "UPDATING_PRIVACY_SUCCESS";
export const UPDATING_PRIVACY_FAILURE = "UPDATING_PRIVACY_FAILURE";

// SparkData Constants
export const UPDATING_SPARK = "UPDATING_SPARK";
export const UPDATING_SPARK_SUCCESS = "UPDATING_SPARK_SUCCESS";
export const UPDATING_SPARK_FAILURE = "UPDATING_SPARK_FAILURE";

//Notification setting Constants
export const UPDATING_NOTIFICATION_SETTING = "UPDATING_NOTIFICATION_SETTING";
export const UPDATED_NOTIFICATION_SETTING_SUCCESS = "UPDATED_NOTIFICATION_SETTING_SUCCESS";
export const UPDATED_NOTIFICATION_SETTING_FAILURE = "UPDATED_NOTIFICATION_SETTING_FAILURE";


//Notification Constants
export const FETCHING_NOTIFICATION = "FETCHING_NOTIFICATION";
export const HIDE_FETCHING_NOTIFICATION = "HIDE_FETCHING_NOTIFICATION";
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_FAILURE = "NOTIFICATION_FAILURE";


//Firebase Chat Constants
export const CHAT_MESSAGE_LOADING = 'CHAT_MESSAGE_LOADING'
export const CHAT_MESSAGE_SUCCESS = 'CHAT_MESSAGE_SUCCESS'
export const CHAT_MESSAGE_ERROR = 'CHAT_MESSAGE_ERROR'
export const CHAT_MESSAGE_UPDATE = 'CHAT_MESSAGE_UPDATE'
export const CHAT_LOAD_MESSAGES_SUCCESS = 'CHAT_LOAD_MESSAGES_SUCCESS'
export const CHAT_LOAD_MESSAGES_ERROR = 'CHAT_LOAD_MESSAGES_ERROR'


//Sidebar Constants
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE'
export const LOGIN_RESPONSE_NULL = 'LOGIN_RESPONSE_NULL'
export const UPDATE_PRIVACY_STATUS = 'UPDATE_PRIVACY_STATUS'
export const ADD_FOLLOWER_SIDE_BAR = 'ADD_FOLLOWER_SIDE_BAR'
export const REMOVE_FOLLOWER_SIDE_BAR = 'REMOVE_FOLLOWER_SIDE_BAR'
export const ADD_FOLLOWINGS_SIDE_BAR = 'ADD_FOLLOWINGS_SIDE_BAR'
export const REMOVE_FOLLOWINGS_SIDE_BAR = 'REMOVE_FOLLOWINGS_SIDE_BAR'

